### ISSUE TITLE
要求提供ViT-H SAM 模型国内链接

### ISSUE THREAD

**Issue by jumbojing** [AP-Kai/segment-anything-pd#1]
要求提供ViT-H SAM 模型国内链接:

* **`默认值`或`vit_h`：[ViT-H SAM 模型。](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_h_4b8939.pth)**
* `vit_l`：[ViT-L SAM 模型。](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_l_0b3195.pth)
* `vit_b`：[ViT-B SAM模型。](https://dl.fbaipublicfiles.com/segment_anything/sam_vit_b_01ec64.pth)

**Comment by AP-Kai** [comment]
请使用convert.py脚本自行转换或戳[这里](https://aistudio.baidu.com/aistudio/datasetdetail/208678)跳转AI Studio下载
